---
title: "p8105_hw6_jw4690"
author: "Jingxi Wang"
date: "2024-11-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rnoaa)
library(broom)
library(modelr)
```

# Problem 1

```{r download and preprocess data}
weather_df <- rnoaa::meteo_pull_monitors(
c("USW00094728"),
var = c("PRCP", "TMIN", "TMAX"),
date_min = "2017-01-01",
date_max = "2017-12-31"
) %>%
mutate(
name = recode(id, USW00094728 = "CentralPark_NY"),
tmin = tmin / 10,
tmax = tmax / 10
) %>%
select(name, id, everything())
```

```{r}
# Create 5000 bootstrap samples

boot_samples <- weather_df %>%
  bootstrap(5000)

# Fit linear models to bootstrap samples

boot_results <- boot_samples %>%
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)), 
    glance = map(models, broom::glance), 
    tidy = map(models, broom::tidy)
  )

# Extract R-squared values

r_squared_results <- boot_results %>%
  unnest(glance) %>%
  select(.id, r.squared)

# Extract log(beta_0 * beta_1)

log_beta_product <- boot_results %>%
  unnest(tidy) %>%
  filter(term %in% c("(Intercept)", "tmin")) %>%
  group_by(.id) %>%
  summarise(log_product = log(prod(estimate)))
```

```{r}
# Confidence intervals for R-squared

conf_intervals_r2 <- r_squared_results %>%
  summarise(
    r_squared_lower = quantile(r.squared, 0.025),
    r_squared_upper = quantile(r.squared, 0.975)
  )

conf_intervals_r2

# Confidence intervals for log(beta_0 * beta_1)

conf_intervals_log_product <- log_beta_product %>%
  summarise(
    log_product_lower = quantile(log_product, 0.025),
    log_product_upper = quantile(log_product, 0.975)
  )

conf_intervals_log_product
```